name: Thermostat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0  # ADDED FOR LOCAL DATABASE
  path: ^1.8.3      # ADDED FOR LOCAL DATABASE PATH MANAGEMENT
  http: ^1.2.1
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  intl: ^0.19.0
  audioplayers: ^6.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  fl_chart: ^0.66.0
  flutter_launcher_icons: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"